# Generated by Django 5.2.4 on 2025-07-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklist',
            name='album',
        ),
        migrations.RemoveField(
            model_name='tracklist',
            name='artists',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='Tracklist',
        ),
    ]
