# Generated by Django 5.2.4 on 2025-08-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumfavorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='albumfavorite',
            name='date_listened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumfavorite',
            name='is_listened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albumfavorite',
            name='list_type',
            field=models.CharField(choices=[('favorite', 'Favorite'), ('listen_later', 'Listen Later')], default='favorite', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='albumfavorite',
            unique_together={('user', 'album', 'list_type')},
        ),
    ]
