# Generated by Django 5.2.4 on 2025-09-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_albumfavorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='enrichment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='is_enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_enriched'], name='albums_albu_is_enri_b1e650_idx'),
        ),
    ]
